### ISSUE TITLE
synchronize to current redis-py

### ISSUE THREAD

**Issue by mikeorr** [ericrasmussen/pyramid_redis_sessions#56]
The package is pinned to redis<=2.9.1 (i.e., redis-py), and the changelog says this is due to an API incompatibility in the 2.10 series (https://github.com/andymccurdy/redis-py/issues/510). That bug is now closed, so can the pin be removed?

**Comment by ericrasmussen** [comment]
I have been very behind on project maintenance -- sorry for that! I updated the version pin and released to PyPI so this should be addressed now. Thanks!
