### ISSUE TITLE
This implementation can not handle nested/multilevel dictionaries properly

### ISSUE THREAD

**Issue by jvanasco** [ericrasmussen/pyramid_redis_sessions#72]
I caught this a month ago in my fork as the issue for many bugs during integration testing -- the current implementation does not catch nested dict values changing.

eg the following code will not automatically persist:
- Request 1: `sesssion.data = {'foo': {'bar': 1}}`
- Request 2: `sesssion.data['foo']['bar'] = 2`

Persisting Request 2 to redis requires an explicit call to `session.changed`

I handled it in my fork by calculating a md5 hash of the from_redis string on from_redis (https://github.com/jvanasco/pyramid_redis_sessions/blob/custom_deployment/pyramid_redis_sessions/session.py#L189-L198).   If an explicit persist is not requested in my  finished callback (https://github.com/jvanasco/pyramid_redis_sessions/blob/custom_deployment/pyramid_redis_sessions/__init__.py#L354-L371), I check to see if the current hashed value is different via a `should_persist` query (https://github.com/jvanasco/pyramid_redis_sessions/blob/custom_deployment/pyramid_redis_sessions/session.py#L52-L61)

there are probably better ways to detect change, but calculating an md5 value is negligible and quick to implement.  

i backported the test case for your version (attached)

```
 TestRedisSession(unittest.TestCase):
    ...
    def test_dict_multilevel(self):
        inst = self._set_up_session_in_Redis_and_makeOne(session_id='test1')
        inst['dict'] = {'foo': {'bar': 1}}
        get_from_inst = inst['dict']['foo']['bar']
        self.assertEqual(get_from_inst, 1)
        session_dict_in_redis = inst.from_redis()['managed_dict']
        get_from_redis = session_dict_in_redis['dict']['foo']['bar']
        self.assertEqual(get_from_redis, 1)
        inst['dict']['foo']['bar'] = 2
        ## requires a call to `changed()` under current system
        # inst.changed()
        session_dict_in_redis2 = inst.from_redis()['managed_dict']
        get_from_redis2 = session_dict_in_redis2['dict']['foo']['bar']
        self.assertEqual(get_from_redis2, 2)
```

**Comment by ericrasmussen** [comment]
This is expected behavior in this case; see
http://docs.pylonsproject.org/projects/pyramid/en/latest/api/interfaces.html#pyramid.interfaces.ISession

I know you're aware of the `changed` method since you mentioned it, but
it's the correct method to use here. The session machinery itself is not
responsible for tracking changes to mutable values.

**Comment by jvanasco** [comment]
wow, that's weird.  I'll open a ticket with Pyramid -- I never noticed that before, and it really works different compared to every other session system i've used.
