### ISSUE TITLE
Possible bug: constructor overwriting reify method

### ISSUE THREAD

**Issue by robvdl** [ericrasmussen/pyramid_redis_sessions#75]
in session.py, line 84 in the constructor says:

self._session_state = self._make_session_state(....

However on line 90 of the same file, there already is a @reify method also called _session_state in the same class, so the way I am reading this, as soon as the constructor is run, that method is "replaced" with an instance variable.

This doesn't sound right.

**Comment by whiteroses** [comment]
Hi @robvdl, I believe I wrote this code. `__init__` doesn't replace the `_session_state` method so much as cover it temporarily with the session state we just created (so that any access to `_session_state`, we get the `__init__`-created instance variable as you say).

When  `invalidate()` deletes `_session_state` in line 152, it reveals the reify-decorated method underneath, ready to create a new `_session_state` next time it is accessed. This relies on how Pyramid's `reify` works.

Probably should've added a comment in `__init__` to clarify this &mdash; will submit a pull request when I have a bit more time.

**Comment by robvdl** [comment]
OK it just makes me a bit uncomfortable that is all, the whole purpose of a @reify method seems to be abused.

Edit: I will try to explain.  The whole purpose of a @reify method is that it is a "cached property" on the class instance.  The idea is that the first time you use this cached property, the code behind it will execute, and execute only ONCE.  Any subsequent use of the @reify property will return it's cached value.  This is intended to be used by compute-heavy properties that don't need to be re-evaluated.

If you intend to replace the value of this property however, then a @reify property is not the right thing to use, as replacing this on the class instance replaces the whole @reify method with a variable instead (I think at least, because it's a little unclear).  If that was the intent, then an instance variable should have been used instead of a @reify property.

Maybe a comment is fine to explain this, but to me if it relies on how Pyramid's @reify works internally, it's a little too magic.

Feel free to close this issue however, as this is just my personal point of view.

**Comment by whiteroses** [comment]
There were long discussions with mmerickel over IRC while working on this, where we specifically discussed this use of `reify`, so I trust I did not abuse its purpose.

This is from Pyramid's documentation for `reify`:

> It operates almost exactly like the Python `@property` decorator, but it puts the result of the method it decorates into the instance dict after the first call, effectively replacing the function it decorates with an instance variable. It is, in Python parlance, a non-data descriptor.

So when we `del` the key from the instance dict, we get access to the non-data descriptor back. Not magic, not reliant on how `reify` works internally, just how non-data descriptors work in Python. Here it's caching the value until invalidate, deleting it on invalidate, and caching it again on next access. I don't see your idea of the "whole purpose" of `reify`, that it must be a one-time thing only, mentioned anywhere in the docs. Looks fine to me.
